server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_product_service_db 
    username: root
    password: "Bidyut@07?"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8788/eureka
    register-with-eureka: true
    fetch-registry: true
